name: Boilerplate deployment

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

      - name: show sha
        run: echo ${{ github.sha }}

  deploy-develop:
    name: "deploy develop"
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Check for changes
        id: check
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse main)" ]; then
            echo "Commit detected on main branch. Running the job."
            echo "::set-output name=run_job::true"
          else
            echo "No new commit on main branch. Skipping the job."
            echo "::set-output name=run_job::false"
          fi
  
      - name: Run job if commit
        if: steps.check.outputs.run_job == 'true'
        run: |
          # Your job commands go here
          echo "Running the job because a new commit was detected on main branch."    
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github.sha }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

  deploy-homolog:
    name: "deploy homolog"
    runs-on: ubuntu-latest
    needs: deploy-develop

    environment:
      name: homolog

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

  deploy-prod:
    name: "deploy prod"
    runs-on: ubuntu-latest
    needs: deploy-homolog

    environment:
      name: prod

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if branch is ahead of main
        run: |
          if ! [ 0 -eq $(git merge-base --is-ancestor ${{ github.sha }} HEAD) ];
          then echo "This branch is not up to date with main";
          exit 1; fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}