name: Boilerplate deployment

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  
  workflow_dispatch:

jobs:
  build-develop:
    name: Build-develop
    runs-on: ubuntu-latest

    environment:
      name: develop

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipemmachado28/boilerplate-dotnet8:develop

  deploy-develop:
    name: "deploy develop"
    runs-on: ubuntu-latest

    needs: build-develop

    environment:
      name: develop

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: pull image
        run: docker pull felipemmachado28/boilerplate-dotnet8:develop

      - name: deploy
        run: echo 'deploy'

      - name: Remove Docker Image
        run: docker rmi yourusername/yourrepository:develop

  build-homolog:
      name: Build-homolog
      runs-on: ubuntu-latest
      needs: deploy-develop

      environment:
        name: homolog

      steps:
        - name: Git checkout
          uses: actions/checkout@v3
  
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: felipemmachado28/boilerplate-dotnet8:develop

  deploy-homolog:
    name: "deploy homolog"
    runs-on: ubuntu-latest
    needs: build-homolog

    environment:
      name: homolog

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

  deploy-prod:
    name: "deploy prod"
    runs-on: ubuntu-latest
    needs: deploy-homolog

    environment:
      name: prod

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}