name: Boilerplate deployment

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

      - name: show sha
        run: echo ${{ github.sha }}

  deploy-develop:
    name: "deploy develop"
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: develop

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github.sha }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

  deploy-homolog:
    name: "deploy homolog"
    runs-on: ubuntu-latest
    needs: deploy-develop

    environment:
      name: homolog

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github }}

      - name: deploy
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}