name: Boilerplate deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    name: Build image and push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

      - name: show sha
        run: echo ${{ github.sha }}

  deploy-development:
    name: "deploy dev ambient"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: show sha
        run: echo ${{ github.sha }}

      - name: deploy dev
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

