name: Boilerplate deployment

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

      - name: show sha
        run: echo ${{ github.sha }}

  migration-develop:
    name: "migration develop"
    runs-on: dev

    needs: build

    environment:
      name: develop

    env:
      DOTNET_INSTALL_DIR: "home/github-install/dotnet"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up migration
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8' # Change this to the version you are using
        
      - name: Restore dependencies
        run: dotnet restore
      
      #- name: Replace Connection String
      #  run: sed -i "s|CONNECTION_STRING|${{ secrets.CONNECTION_STRING }}|" API/appsettings.json

      - name: Build
        run: dotnet build "API/API.csproj" -c Release
  
      - name: Run EF Core Migrations
        run: |
          dotnet ef database update --startup-project API/API.csproj -p Infra/Infra.csproj -v -c ApplicationDbContext
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING  }}
      

  deploy-develop:
    name: "deploy develop"
    runs-on: dev

    needs: migration-develop

    environment:
      name: develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: pull image
        run: docker pull felipemmachado28/boilerplate-dotnet8:${{ github.sha }}

      - name: run docker container
        run: docker run -d -p 8080:5001 |
            -e ConnectionStrings__connectionString='${{ secrets.CONNECTION_STRING }}'
            --name boilerplate-dotnet8:dev felipemmachado28/boilerplate-dotnet8